Reading data from csv

In [1]:
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report, accuracy_score, confusion_matrix, roc_curve, auc

df = pd.read_csv('enron_spam_data.csv')
display(df)

,Message ID,Subject,Message,Spam/Ham,Date
0,0,christmas tree farm pictures,NaN,ham,1999-12-10
1,1,"vastar resources , inc .","gary , production from the high island larger ...",ham,1999-12-13
2,2,calpine daily gas nomination,- calpine daily gas nomination 1 . doc,ham,1999-12-14
3,3,re : issue,fyi - see note below - already done .\nstella\...,ham,1999-12-14
4,4,meter 7268 nov allocation,fyi .\n- - - - - - - - - - - - - - - - - - - -...,ham,1999-12-14
...,...,...,...,...,...
33711,33711,= ? iso - 8859 - 1 ? q ? good _ news _ c = eda...,"hello , welcome to gigapharm onlinne shop .\np...",spam,2005-07-29
33712,33712,all prescript medicines are on special . to be...,i got it earlier than expected and it was wrap...,spam,2005-07-29
33713,33713,the next generation online pharmacy .,are you ready to rock on ? let the man in you ...,spam,2005-07-30
33714,33714,bloow in 5 - 10 times the time,learn how to last 5 - 10 times longer in\nbed ...,spam,2005-07-30
33715,33715,"dear sir , i am interested in it",hi : )\ndo you need some softwares ? i can giv...,spam,2005-07-31

Data Cleaning

In [2]:
import re

def regexClean(message_content):
    # convert everything to string
    # getting a "passing a float" error otherwise
    message_content = str(message_content) 
    
    # remove all URLs
    message_content = re.sub(r'(http|https|ftp)://[a-zA-Z0-9\\./]+', ' ', str(message_content)) 

    # remove all emails
    message_content = re.sub(r'[A-Za-z0-9._\\-]+@[A-Za-z0-9-]*\\.[a-z]{2,3}','',str(message_content))

    # remove all tags
    # https://stackoverflow.com/questions/9662346/python-code-to-remove-html-tags-from-a-string
    message_content = re.sub(r'<[^<]+?>', '', str(message_content)) 

    # remove newline
    message_content = message_content.replace('\n', ' ')

    # convert all chars to lowercase
    message_content = message_content.lower()
    return message_content

# make a copy of the df 
df_with_punct_numb_removed = df.copy();

df['Cleaned_Message'] = df['Message'].apply(regexClean)

print(df[['Message', 'Cleaned_Message']].head())
df_with_punct_numb_removed.head()

                                             Message  \
0                                                NaN
1  gary , production from the high island larger ...
2             - calpine daily gas nomination 1 . doc
3  fyi - see note below - already done .\nstella\...
4  fyi .\n- - - - - - - - - - - - - - - - - - - -...

                                     Cleaned_Message
0                                                nan
1  gary , production from the high island larger ...
2             - calpine daily gas nomination 1 . doc
3  fyi - see note below - already done . stella -...
4  fyi . - - - - - - - - - - - - - - - - - - - - ...

,Message ID,Subject,Message,Spam/Ham,Date
0,0,christmas tree farm pictures,NaN,ham,1999-12-10
1,1,"vastar resources , inc .","gary , production from the high island larger ...",ham,1999-12-13
2,2,calpine daily gas nomination,- calpine daily gas nomination 1 . doc,ham,1999-12-14
3,3,re : issue,fyi - see note below - already done .\nstella\...,ham,1999-12-14
4,4,meter 7268 nov allocation,fyi .\n- - - - - - - - - - - - - - - - - - - -...,ham,1999-12-14

punctuation and digits removed

In [3]:
from string import punctuation

def punct_removal(message_content):
    message_content = str(message_content)
    
    # https://regexr.com/
    
    # remove digits
    message_content = re.sub(r'\d+', ' ', message_content)

    # remove all non-alphabetic characters
    message_content = message_content.replace(r'[^a-zA-Z]', '') 

    #remove punctuation
    # https://stackoverflow.com/questions/265960/best-way-to-strip-punctuation-from-a-string
    message_content = message_content.translate(str.maketrans('', '', punctuation))
    
    return message_content

df_with_punct_numb_removed['Cleaned_Message'] = df_with_punct_numb_removed['Message'].apply(punct_removal)

display(df_with_punct_numb_removed)

,Message ID,Subject,Message,Spam/Ham,Date,Cleaned_Message
0,0,christmas tree farm pictures,NaN,ham,1999-12-10,nan
1,1,"vastar resources , inc .","gary , production from the high island larger ...",ham,1999-12-13,gary production from the high island larger b...
2,2,calpine daily gas nomination,- calpine daily gas nomination 1 . doc,ham,1999-12-14,calpine daily gas nomination doc
3,3,re : issue,fyi - see note below - already done .\nstella\...,ham,1999-12-14,fyi see note below already done \nstella\n ...
4,4,meter 7268 nov allocation,fyi .\n- - - - - - - - - - - - - - - - - - - -...,ham,1999-12-14,fyi \n forwarded by lauri...
...,...,...,...,...,...,...
33711,33711,= ? iso - 8859 - 1 ? q ? good _ news _ c = eda...,"hello , welcome to gigapharm onlinne shop .\np...",spam,2005-07-29,hello welcome to gigapharm onlinne shop \npre...
33712,33712,all prescript medicines are on special . to be...,i got it earlier than expected and it was wrap...,spam,2005-07-29,i got it earlier than expected and it was wrap...
33713,33713,the next generation online pharmacy .,are you ready to rock on ? let the man in you ...,spam,2005-07-30,are you ready to rock on let the man in you r...
33714,33714,bloow in 5 - 10 times the time,learn how to last 5 - 10 times longer in\nbed ...,spam,2005-07-30,learn how to last times longer in\nbed ...
33715,33715,"dear sir , i am interested in it",hi : )\ndo you need some softwares ? i can giv...,spam,2005-07-31,hi \ndo you need some softwares i can give y...

# TFIDF

In [4]:
# Vectorize the text data
vectorizer = TfidfVectorizer(max_features=3000)
X = vectorizer.fit_transform(df_with_punct_numb_removed['Cleaned_Message']).toarray()

# Convert the vectorized data to a DataFrame for better visualization
vectorized_df = pd.DataFrame(X, columns=vectorizer.get_feature_names_out())

# Display the first few rows of the vectorized data
print(vectorized_df.head())

    aa  ability  able     about  above  absolutely  abuse   ac  accept  \
0  0.0      0.0   0.0  0.000000    0.0         0.0    0.0  0.0     0.0
1  0.0      0.0   0.0  0.021487    0.0         0.0    0.0  0.0     0.0
2  0.0      0.0   0.0  0.000000    0.0         0.0    0.0  0.0     0.0
3  0.0      0.0   0.0  0.000000    0.0         0.0    0.0  0.0     0.0
4  0.0      0.0   0.0  0.000000    0.0         0.0    0.0  0.0     0.0

   acceptance  ...   yo  york       you  young  your  yours  yourself  zero  \
0         0.0  ...  0.0   0.0  0.000000    0.0   0.0    0.0       0.0   0.0
1         0.0  ...  0.0   0.0  0.011551    0.0   0.0    0.0       0.0   0.0
2         0.0  ...  0.0   0.0  0.000000    0.0   0.0    0.0       0.0   0.0
3         0.0  ...  0.0   0.0  0.034688    0.0   0.0    0.0       0.0   0.0
4         0.0  ...  0.0   0.0  0.000000    0.0   0.0    0.0       0.0   0.0

   zimin  zone
0    0.0   0.0
1    0.0   0.0
2    0.0   0.0
3    0.0   0.0
4    0.0   0.0

[5 rows x 3000 columns]